
const data = [
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579385/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_24.png',
    type: 'Webinar',
    topic: 'COVID-19',
    content: 'COVID-19 Outbreak: How to Use Telehealth as a Key Element of your Infection Control and Prevention strategy',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579385/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_24.png',
    type: 'Webinar',
    topic: 'COVID-19',
    content: 'COVID-19 Outbreak: How to Use Telehealth as a Key Element of your Infection Control and Prevention strategy',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579385/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_24.png',
    type: 'Webinar',
    topic: 'COVID-19',
    content: 'COVID-19 Outbreak: How to Use Telehealth as a Key Element of your Infection Control and Prevention strategy',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
  {
    url: 'https://res.cloudinary.com/dx0nauane/image/upload/v1594579353/mDoc/mdoc_image/covid-response/covid%20response/Mask_Group_12.png',
    type: 'Webinar',
    topic: 'Health System',
    content: 'Intermountain Healthcare: Optimizing the Provider-Patient Digital Experience Through Telehealth Interoperability',
  },
]

export default data;
